@startuml
'https://plantuml.com/activity-diagram-beta

start
: Two users joined to play game;
repeat
    :PlayerA makes a move, move some piece;
    :PlayerB makes a move, move some piece - could also remove some of compitetor piece;

repeat while(any one king is killed)
stop

@enduml
